### ISSUE TITLE
Vermiste Bestanden

### ISSUE THREAD

**Issue by pspletinckx** [NicoVerbeeke/BackEndZomer2015#1]
Er zijn verscheidene bestanden waar het project naar verwijst die nog niet in de git zitten.
bijvoorbeeld Entities/projectenAug.edmx

Kijk eens of je deze kan toevoegen aan de index, verifiëer door op github te kijken.

**Comment by NicoVerbeeke** [comment]
De bestanden die werden gecommit en gesynced vanuit VS stonden nog open in de desktop client van Github om gecommit en gesynced te worden. Deze issue werd ondertussen al opgelost, geverifieerd door mijzelf en Pieter
